# Core & settings
from core import models
from django.conf import settings
import requests
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.management import call_command
import time
from django.views.generic.base import RedirectView


def get_api_info(api_url):
    time_delay = 0
    r = False
    while not r:
        try:
            time.sleep(time_delay)
            r = requests.get(api_url)
        except ConnectionError:
            # Add 5 seconds onto the time delay
            time_delay += 15
            # Print out so we can monitor it
            print('Timed out, trying again in ' + time_delay + ' seconds')
    return r


class ResetTaxaTree(RedirectView):
    iucn_sa_occurrences = {}
    pattern_name = 'admin'

    def get_redirect_url(self, *args, **kwargs):
        self.reset_taxa_tree()
        return super(ResetTaxaTree, self).get_redirect_url(*args, **kwargs)

    def reset_taxa_tree(self):
        birdlife_checklist = ['Diomedea amsterdamensis',
                              'Thalassarche chlororhynchos',
                              'Thalassarche melanophrys',
                              'Thalassarche bulleri',
                              'Thalassarche eremita',
                              'Thalassarche chrysostoma',
                              'Thalassarche carteri',
                              'Phoebastria immutabilis',
                              'Phoebetria palpebrata',
                              'Diomedea sanfordi',
                              'Thalassarche salvini',
                              'Thalassarche cauta',
                              'Phoebetria fusca',
                              'Diomedea epomophora',
                              'Diomedea dabbenena',
                              'Diomedea exulans',
                              'Apalis thoracica',
                              'Apalis ruddi',
                              'Apalis flavida',
                              'Recurvirostra avosetta',
                              'Turdoides jardineii',
                              'Turdoides bicolor',
                              'Tricholaema leucomelas',
                              'Lybius torquatus',
                              'Trachyphonus vaillantii',
                              'Stactolaema olivacea',
                              'Stactolaema leucotis',
                              'Terathopius ecaudatus',
                              'Batis capensis',
                              'Batis molitor',
                              'Batis pririt',
                              'Batis fratrum',
                              'Merops persicus',
                              'Merops apiaster',
                              'Merops pusillus',
                              'Merops superciliosus',
                              'Merops nubicoides',
                              'Merops hirundineus',
                              'Merops bullockoides',
                              'Merops albicollis',
                              'Euplectes orix',
                              'Euplectes capensis',
                              'Euplectes afer',
                              'Ixobrychus sturmii',
                              'Botaurus stellaris',
                              'Ixobrychus minutus',
                              'Lioptilus nigricapillus',
                              'Sylvia atricapilla',
                              'Telophorus zeylonus',
                              'Sula leucogaster',
                              'Sula sula',
                              'Laniarius ferrugineus',
                              'Laniarius major',
                              'Smithornis capensis',
                              'Phyllastrephus terrestris',
                              'Nilaus afer',
                              'Pycnonotus nigricans',
                              'Pycnonotus capensis',
                              'Pycnonotus tricolor',
                              'Emberiza capensis',
                              'Emberiza tahapisi',
                              'Emberiza flaviventris',
                              'Emberiza impetuani',
                              'Chlorophoneus nigrifrons',
                              'Chlorophoneus viridis',
                              'Malaconotus blanchoti',
                              'Chlorophoneus olivaceus',
                              'Chlorophoneus sulfureopectus',
                              'Lissotis melanogaster',
                              'Neotis denhami',
                              'Ardeotis kori',
                              'Neotis ludwigii',
                              'Turnix nanus',
                              'Turnix sylvaticus',
                              'Turnix hottentottus',
                              'Buteo buteo',
                              'Pernis apivorus',
                              'Buteo trizonatus',
                              'Buteo rufofuscus',
                              'Kaupifalco monogrammicus',
                              'Camaroptera brachyura',
                              'Camaroptera brevicaudata',
                              'Serinus alario',
                              'Crithagra atrogularis',
                              'Crithagra sulphurata',
                              'Serinus canicollis',
                              'Crithagra scotops',
                              'Crithagra citrinipectus',
                              'Crithagra albogularis',
                              'Crithagra flaviventris',
                              'Crithagra mozambica',
                              'Fringilla coelebs',
                              'Myrmecocichla formicivora',
                              'Pentholaea arnotti',
                              'Pinarornis plumosus',
                              'Campicoloides bifasciata',
                              'Cercomela familiaris',
                              'Cercomela schlegelii',
                              'Thamnolaea cinnamomeiventris',
                              'Cercomela sinuata',
                              'Cercomela tractrac',
                              'Cisticola textrix',
                              'Cisticola natalensis',
                              'Cisticola aridulus',
                              'Cisticola subruficapilla',
                              'Cisticola aberrans',
                              'Cisticola tinniens',
                              'Cisticola cinnamomeus',
                              'Cisticola chiniana',
                              'Cisticola erythrops',
                              'Cisticola galactotes',
                              'Cisticola rufilatus',
                              'Cisticola lais',
                              'Cisticola ayresii',
                              'Cisticola juncidis',
                              'Fulica cristata',
                              'Phalacrocorax neglectus',
                              'Phalacrocorax capensis',
                              'Phalacrocorax coronatus',
                              'Phalacrocorax africanus',
                              'Phalacrocorax lucidus',
                              'Centropus grillii',
                              'Centropus burchellii',
                              'Centropus senegalensis',
                              'Rhinoptilus chalcopterus',
                              'Cursorius rufus',
                              'Rhinoptilus africanus',
                              'Cursorius temminckii',
                              'Rhinoptilus cinctus',
                              'Crecopsis egregia',
                              'Porzana pusilla',
                              'Amaurornis flavirostra',
                              'Crex crex',
                              'Porzana parva',
                              'Porzana porzana',
                              'Aenigmatolimnas marginalis',
                              'Anthropoides paradiseus',
                              'Balearica regulorum',
                              'Bugeranus carunculatus',
                              'Sylvietta rufescens',
                              'Corvus capensis',
                              'Corvus splendens',
                              'Corvus albus',
                              'Cuculus gularis',
                              'Chrysococcyx cupreus',
                              'Cercococcyx montanus',
                              'Cuculus clamosus',
                              'Cuculus canorus',
                              'Chrysococcyx caprius',
                              'Clamator glandarius',
                              'Clamator jacobinus',
                              'Chrysococcyx klaas',
                              'Clamator levaillantii',
                              'Cuculus rochii',
                              'Cuculus solitarius',
                              'Pachycoccyx audeberti',
                              'Campephaga flava',
                              'Coracina caesia',
                              'Coracina pectoralis',
                              'Numenius arquata',
                              'Anhinga rufa',
                              'Streptopelia decipiens',
                              'Turtur afer',
                              'Streptopelia capicola',
                              'Turtur chalcospilos',
                              'Streptopelia turtur',
                              'Streptopelia senegalensis',
                              'Columba larvata',
                              'Oena capensis',
                              'Streptopelia semitorquata',
                              'Columba livia',
                              'Turtur tympanistria',
                              'Limnodromus semipalmatus',
                              'Dicrurus adsimilis',
                              'Dicrurus ludwigii',
                              'Anas sparsa',
                              'Dendrocygna bicolor',
                              'Sarkidiornis melanotos',
                              'Oxyura maccoa',
                              'Thalassornis leuconotus',
                              'Dendrocygna viduata',
                              'Anas undulata',
                              'Calidris alpina',
                              'Haliaeetus vocifer',
                              'Aquila spilogaster',
                              'Hieraaetus ayresii',
                              'Circaetus pectoralis',
                              'Hieraaetus pennatus',
                              'Circaetus cinereus',
                              'Stephanoaetus coronatus',
                              'Clanga pomarina',
                              'Lophaetus occipitalis',
                              'Polemaetus bellicosus',
                              'Circaetus fasciolatus',
                              'Aquila nipalensis',
                              'Aquila rapax',
                              'Aquila verreauxii',
                              'Hieraaetus wahlbergi',
                              'Egretta alba',
                              'Egretta garzetta',
                              'Egretta vinaceigula',
                              'Egretta thula',
                              'Bubulcus ibis',
                              'Egretta intermedia',
                              'Eremomela usticollis',
                              'Eremomela scotops',
                              'Eremomela gregalis',
                              'Eremomela icteropygialis',
                              'Falco amurensis',
                              'Falco eleonorae',
                              'Falco biarmicus',
                              'Falco peregrinus',
                              'Polihierax semitorquatus',
                              'Falco vespertinus',
                              'Falco chicquera',
                              'Falco concolor',
                              'Falco fasciinucha',
                              'Anomalospiza imberbis',
                              'Amadina fasciata',
                              'Amadina erythrocephala',
                              'Sporopipes squamifrons',
                              'Podica senegalensis',
                              'Lagonosticta rubricata',
                              'Lagonosticta rhodopareia',
                              'Lagonosticta senegala',
                              'Lanius collaris',
                              'Phoenicopterus roseus',
                              'Phoeniconaias minor',
                              'Sarothrura elegans',
                              'Sarothrura rufa',
                              'Sarothrura boehmi',
                              'Sarothrura affinis',
                              'Sarothrura ayresi',
                              'Muscicapa adusta',
                              'Terpsiphone viridis',
                              'Muscicapa caerulescens',
                              'Bias musicus',
                              'Trochocercus cyanomelas',
                              'Bradornis infuscatus',
                              'Ficedula albicollis',
                              'Stenostira scita',
                              'Sigelus silens',
                              'Myioparus plumbeus',
                              'Bradornis mariquensis',
                              'Bradornis pallidus',
                              'Melaenornis pammelaina',
                              'Muscicapa striata',
                              'Peliperdix coqui',
                              'Dendroperdix sephaena',
                              'Scleroptila afra',
                              'Scleroptila gutturalis',
                              'Scleroptila levaillantii',
                              'Scleroptila shelleyi',
                              'Fregata minor',
                              'Fregata ariel',
                              'Fulmarus glacialoides',
                              'Porphyrio alleni',
                              'Porphyrio martinicus',
                              'Morus serrator',
                              'Morus capensis',
                              'Anas querquedula',
                              'Corythaixoides concolor',
                              'Limosa lapponica',
                              'Limosa limosa',
                              'Limosa haemastica',
                              'Nettapus auritus',
                              'Alopochen aegyptiaca',
                              'Plectropterus gambensis',
                              'Accipiter tachiro',
                              'Melierax metabates',
                              'Melierax gabar',
                              'Melierax canorus',
                              'Sphenoeacus afer',
                              'Podiceps nigricollis',
                              'Podiceps cristatus',
                              'Tachybaptus ruficollis',
                              'Andropadus importunus',
                              'Chlorocichla flaviventris',
                              'Phyllastrephus flavostriatus',
                              'Tringa nebularia',
                              'Guttera pucherani',
                              'Numida meleagris',
                              'Chroicocephalus ridibundus',
                              'Leucophaeus pipixcan',
                              'Chroicocephalus cirrocephalus',
                              'Chroicocephalus hartlaubii',
                              'Larus dominicanus',
                              'Larus fuscus',
                              'Xema sabini',
                              'Chroicocephalus genei',
                              'Scopus umbretta',
                              'Circus ranivorus',
                              'Circus maurus',
                              'Circus pygargus',
                              'Circus macrourus',
                              'Circus aeruginosus',
                              'Aviceda cuculoides',
                              'Polyboroides typus',
                              'Macheiramphus alcinus',
                              'Prionops scopifrons',
                              'Prionops retzii',
                              'Prionops plumatus',
                              'Egretta ardesiaca',
                              'Nycticorax nycticorax',
                              'Ardea melanocephala',
                              'Ardea goliath',
                              'Butorides striata',
                              'Ardea cinerea',
                              'Egretta caerulea',
                              'Ardea purpurea',
                              'Ardeola rufiventris',
                              'Ardeola ralloides',
                              'Gorsachius leuconotus',
                              'Falco cuvierii',
                              'Falco subbuteo',
                              'Prodotiscus regulus',
                              'Indicator indicator',
                              'Indicator minor',
                              'Indicator variegatus',
                              'Upupa africana',
                              'Tockus nasutus',
                              'Tockus alboterminatus',
                              'Bucorvus leadbeateri',
                              'Tockus rufirostris',
                              'Tockus leucomelas',
                              'Bycanistes bucinator',
                              'Hyliota australis',
                              'Threskiornis aethiopicus',
                              'Plegadis falcinellus',
                              'Bostrychia hagedash',
                              'Geronticus calvus',
                              'Vidua funerea',
                              'Vidua purpurascens',
                              'Vidua chalybeata',
                              'Actophilornis africanus',
                              'Microparra capensis',
                              'Stercorarius longicaudus',
                              'Stercorarius parasiticus',
                              'Falco dickinsoni',
                              'Falco rupicoloides',
                              'Falco naumanni',
                              'Falco rupicolus',
                              'Ispidina picta',
                              'Halcyon albiventris',
                              'Megaceryle maxima',
                              'Halcyon leucocephala',
                              'Alcedo semitorquata',
                              'Alcedo cristata',
                              'Halcyon senegaloides',
                              'Ceryle rudis',
                              'Halcyon chelicuti',
                              'Halcyon senegalensis',
                              'Milvus migrans',
                              'Elanus caeruleus',
                              'Milvus aegyptius',
                              'Rissa tridactyla',
                              'Calidris tenuirostris',
                              'Calidris canutus',
                              'Eupodotis caerulescens',
                              'Eupodotis vigorsii',
                              'Afrotis afraoides',
                              'Lophotis ruficrista',
                              'Afrotis afra',
                              'Eupodotis senegalensis',
                              'Vanellus senegallus',
                              'Vanellus melanopterus',
                              'Vanellus armatus',
                              'Vanellus coronatus',
                              'Vanellus crassirostris',
                              'Vanellus lugubris',
                              'Vanellus albiceps',
                              'Certhilauda brevirostris',
                              'Calendulauda barlowi',
                              'Eremopterix australis',
                              'Spizocorys fringillaris',
                              'Mirafra apiata',
                              'Certhilauda curvirostris',
                              'Eremopterix leucotis',
                              'Pinarocorys nigricans',
                              'Mirafra fasciolata',
                              'Certhilauda semitorquata',
                              'Calendulauda africanoides',
                              'Mirafra rufocinnamomea',
                              'Eremopterix verticalis',
                              'Calendulauda albescens',
                              'Certhilauda subcoronata',
                              'Galerida magnirostris',
                              'Mirafra cheniana',
                              'Mirafra passerina',
                              'Spizocorys conirostris',
                              'Calendulauda burra',
                              'Calandrella cinerea',
                              'Heteromirafra ruddi',
                              'Mirafra africana',
                              'Calendulauda sabota',
                              'Spizocorys sclateri',
                              'Certhilauda chuana',
                              'Chersomanes albofasciata',
                              'Spizocorys starki',
                              'Macronyx capensis',
                              'Macronyx ameliae',
                              'Macronyx croceus',
                              'Agapornis roseicollis',
                              'Ceuthmochares australis',
                              'Anas platyrhynchos',
                              'Lonchura cucullata',
                              'Lonchura fringilloides',
                              'Lonchura nigriceps',
                              'Riparia cincta',
                              'Riparia paludicola',
                              'Delichon urbicum',
                              'Hirundo fuligula',
                              'Riparia riparia',
                              'Gallinula chloropus',
                              'Gallinula angulata',
                              'Urocolius indicus',
                              'Colius striatus',
                              'Colius colius',
                              'Acridotheres tristis',
                              'Cisticola fulvicapilla',
                              'Nicator gularis',
                              'Luscinia luscinia',
                              'Caprimulgus europaeus',
                              'Caprimulgus pectoralis',
                              'Caprimulgus tristigma',
                              'Caprimulgus vexillarius',
                              'Caprimulgus rufigena',
                              'Caprimulgus fossii',
                              'Caprimulgus natalensis',
                              'Anous stolidus',
                              'Anous tenuirostris',
                              'Anastomus lamelligerus',
                              'Oriolus auratus',
                              'Oriolus larvatus',
                              'Oriolus oriolus',
                              'Pandion haliaetus',
                              'Struthio camelus',
                              'Tyto capensis',
                              'Otus senegalensis',
                              'Strix woodfordii',
                              'Bubo capensis',
                              'Asio capensis',
                              'Scotopelia peli',
                              'Ptilopsis granti',
                              'Bubo africanus',
                              'Bubo lacteus',
                              'Tyto alba',
                              'Glaucidium capense',
                              'Glaucidium perlatum',
                              'Buphagus erythrorynchus',
                              'Buphagus africanus',
                              'Haematopus moquini',
                              'Haematopus ostralegus',
                              'Rostratula benghalensis',
                              'Psittacula krameri',
                              'Poicephalus cryptoxanthus',
                              'Poicephalus robustus',
                              'Poicephalus fuscicollis',
                              'Poicephalus meyeri',
                              'Alectoris chukar',
                              'Pavo cristatus',
                              'Pelecanus onocrotalus',
                              'Pelecanus rufescens',
                              'Anthoscopus minutus',
                              'Anthoscopus caroli',
                              'Spheniscus demersus',
                              'Aptenodytes patagonicus',
                              'Eudyptes chrysolophus',
                              'Eudyptes moseleyi',
                              'Eudyptes chrysocome',
                              'Thalassoica antarctica',
                              'Pterodroma incerta',
                              'Pterodroma baraui',
                              'Fregetta tropica',
                              'Halobaena caerulea',
                              'Hydrobates pelagicus',
                              'Pterodroma macroptera',
                              'Procellaria cinerea',
                              'Garrodia nereis',
                              'Lugensa brevirostris',
                              'Oceanodroma leucorhoa',
                              'Oceanodroma matsudairae',
                              'Macronectes halli',
                              'Daption capense',
                              'Pterodroma mollis',
                              'Macronectes giganteus',
                              'Procellaria conspicillata',
                              'Fregetta grallaria',
                              'Procellaria aequinoctialis',
                              'Pelagodroma marina',
                              'Pterodroma lessonii',
                              'Oceanites oceanicus',
                              'Gymnoris superciliaris',
                              'Phalaropus fulicarius',
                              'Phalaropus lobatus',
                              'Phalaropus tricolor',
                              'Treron calvus',
                              'Columba arquatrix',
                              'Columba delegorguei',
                              'Columba guinea',
                              'Anas acuta',
                              'Anthus cinnamomeus',
                              'Anthus crenatus',
                              'Anthus vaalensis',
                              'Anthus caffer',
                              'Tmetothylacus tenellus',
                              'Anthus similis',
                              'Anthus hoeschi',
                              'Anthus leucophrys',
                              'Anthus cervinus',
                              'Anthus brachyurus',
                              'Anthus lineiventris',
                              'Anthus trivialis',
                              'Anthus chloris',
                              'Pitta angolensis',
                              'Pluvialis dominica',
                              'Charadrius asiaticus',
                              'Charadrius pallidus',
                              'Charadrius hiaticula',
                              'Dromas ardeola',
                              'Charadrius leschenaultii',
                              'Pluvialis squatarola',
                              'Charadrius pecuarius',
                              'Charadrius mongolus',
                              'Pluvialis fulva',
                              'Charadrius tricollaris',
                              'Charadrius marginatus',
                              'Netta erythrophthalma',
                              'Glareola nordmanni',
                              'Glareola pratincola',
                              'Glareola nuchalis',
                              'Prinia flavicans',
                              'Prinia hypoxantha',
                              'Prinia maculosa',
                              'Prinia subflava',
                              'Pachyptila desolata',
                              'Pachyptila vittata',
                              'Pachyptila turtur',
                              'Pachyptila salvini',
                              'Pachyptila belcheri',
                              'Dryoscopus cubla',
                              'Pytilia melba',
                              'Pytilia afra',
                              'Ortygospiza fuscocrissa',
                              'Excalfactoria adansonii',
                              'Coturnix coturnix',
                              'Coturnix delegorguei',
                              'Quelea quelea',
                              'Quelea erythrops',
                              'Rallus caerulescens',
                              'Corvus albicollis',
                              'Tringa totanus',
                              'Tringa erythropus',
                              'Phoenicurus phoenicurus',
                              'Cossypha caffra',
                              'Cossypha dichroa',
                              'Cossypha natalensis',
                              'Cossypha heuglini',
                              'Cossypha humeralis',
                              'Erythropygia quadrivirgata',
                              'Erythropygia signata',
                              'Erythropygia paena',
                              'Erythropygia coryphoeus',
                              'Erythropygia leucophrys',
                              'Pogonocichla stellata',
                              'Chaetops frenatus',
                              'Chaetops aurantius',
                              'Eurystomus glaucurus',
                              'Coracias garrulus',
                              'Coracias caudatus',
                              'Coracias naevius',
                              'Coracias spatulatus',
                              'Philomachus pugnax',
                              'Calidris alba',
                              'Pterocles burchelli',
                              'Pterocles bicinctus',
                              'Pterocles namaqua',
                              'Pterocles gutturalis',
                              'Calidris bairdii',
                              'Limicola falcinellus',
                              'Tryngites subruficollis',
                              'Actitis hypoleucos',
                              'Calidris ferruginea',
                              'Tringa ochropus',
                              'Tringa stagnatilis',
                              'Calidris melanotos',
                              'Xenus cinereus',
                              'Calidris fuscicollis',
                              'Tringa glareola',
                              'Psalidoprocne pristoptera',
                              'Rhinopomastus cyanomelas',
                              'Sagittarius serpentarius',
                              'Crithagra leucoptera',
                              'Crithagra gularis',
                              'Calonectris borealis',
                              'Puffinus carneipes',
                              'Puffinus gravis',
                              'Puffinus assimilis',
                              'Puffinus puffinus',
                              'Calonectris diomedea',
                              'Puffinus griseus',
                              'Calonectris leucomelas',
                              'Puffinus bailloni',
                              'Puffinus pacificus',
                              'Chionis albus',
                              'Tadorna cana',
                              'Accipiter badius',
                              'Anas smithii',
                              'Laniarius atrococcineus',
                              'Lanius minor',
                              'Corvinella melanoleuca',
                              'Lanius collurio',
                              'Eurocephalus anguitimens',
                              'Crithagra totta',
                              'Crithagra symonsi',
                              'Rynchops flavirostris',
                              'Rynchops niger',
                              'Stercorarius pomarinus',
                              'Stercorarius maccormicki',
                              'Stercorarius antarcticus',
                              'Gallinago nigripennis',
                              'Gallinago media',
                              'Plocepasser mahali',
                              'Passer melanurus',
                              'Passer motitensis',
                              'Passer domesticus',
                              'Passer diffusus',
                              'Accipiter melanoleucus',
                              'Accipiter minullus',
                              'Accipiter ovampensis',
                              'Accipiter rufiventris',
                              'Neafrapus boehmi',
                              'Telacanthura ussheri',
                              'Platalea alba',
                              'Pternistis capensis',
                              'Pternistis natalensis',
                              'Pternistis adspersus',
                              'Pternistis afer',
                              'Pternistis swainsonii',
                              'Notopholia corrusca',
                              'Lamprotornis australis',
                              'Lamprotornis nitens',
                              'Sturnus vulgaris',
                              'Lamprotornis chalybaeus',
                              'Lamprotornis mevesii',
                              'Lamprotornis elisabeth',
                              'Onychognathus nabouroup',
                              'Lamprotornis bicolor',
                              'Onychognathus morio',
                              'Cinnyricinclus leucogaster',
                              'Creatophora cinerea',
                              'Himantopus himantopus',
                              'Calidris minuta',
                              'Calidris subminuta',
                              'Calidris ruficollis',
                              'Calidris temminckii',
                              'Saxicola torquatus',
                              'Ciconia abdimii',
                              'Ciconia nigra',
                              'Leptoptilos crumeniferus',
                              'Ephippiorhynchus senegalensis',
                              'Ciconia ciconia',
                              'Ciconia episcopus',
                              'Mycteria ibis',
                              'Promerops cafer',
                              'Promerops gurneyi',
                              'Chalcomitra amethystina',
                              'Anthodiaeta collaris',
                              'Cinnyris fuscus',
                              'Cinnyris afer',
                              'Cyanomitra veroxii',
                              'Nectarinia famosa',
                              'Cinnyris mariquensis',
                              'Cinnyris neergaardi',
                              'Cyanomitra olivacea',
                              'Anthobaphes violacea',
                              'Anthreptes reichenowi',
                              'Cinnyris bifasciatus',
                              'Chalcomitra senegalensis',
                              'Cinnyris chalybeus',
                              'Cinnyris venustus',
                              'Cinnyris talatala',
                              'Hirundo rustica',
                              'Hirundo atrocaerulea',
                              'Cecropis cucullata',
                              'Pseudhirundo griseopyga',
                              'Cecropis abyssinica',
                              'Cecropis senegalensis',
                              'Hirundo dimidiata',
                              'Cecropis semirufa',
                              'Petrochelidon spilodera',
                              'Hirundo albigularis',
                              'Hirundo smithii',
                              'Porphyrio madagascariensis',
                              'Cygnus olor',
                              'Apus barbatus',
                              'Cypsiurus parvus',
                              'Tachymarptis melba',
                              'Apus bradfieldi',
                              'Apus apus',
                              'Apus horus',
                              'Apus affinis',
                              'Apus caffer',
                              'Tchagra senegalus',
                              'Tchagra australis',
                              'Tchagra tchagra',
                              'Anas capensis',
                              'Anas hottentota',
                              'Anas erythrorhyncha',
                              'Sterna vittata',
                              'Sterna paradisaea',
                              'Chlidonias niger',
                              'Sterna sumatrana',
                              'Onychoprion anaethetus',
                              'Sterna caspia',
                              'Sterna hirundo',
                              'Sterna balaenarum',
                              'Sterna elegans',
                              'Gelochelidon nilotica',
                              'Thalasseus bengalensis',
                              'Sterna albifrons',
                              'Sterna dougallii',
                              'Thalasseus sandvicensis',
                              'Onychoprion fuscatus',
                              'Thalasseus bergii',
                              'Chlidonias hybrida',
                              'Sterna repressa',
                              'Chlidonias leucopterus',
                              'Burhinus capensis',
                              'Burhinus vermiculatus',
                              'Monticola rupestris',
                              'Cichladusa arquata',
                              'Turdus litsitsirupa',
                              'Turdus smithi',
                              'Turdus libonyanus',
                              'Turdus olivaceus',
                              'Geokichla gurneyi',
                              'Monticola explorator',
                              'Monticola brevipes',
                              'Geokichla guttata',
                              'Pogoniulus pusillus',
                              'Pogoniulus chrysoconus',
                              'Pogoniulus bilineatus',
                              'Sylvia subcaerulea',
                              'Sylvia layardi',
                              'Parus cinerascens',
                              'Parus afer',
                              'Parus niger',
                              'Apaloderma narina',
                              'Phaethon aethereus',
                              'Phaethon rubricauda',
                              'Phaethon lepturus',
                              'Tauraco corythaix',
                              'Tauraco livingstonii',
                              'Tauraco porphyreolophus',
                              'Arenaria interpres',
                              'Mandingoa nitidula',
                              'Hypargos margaritatus',
                              'Hypargos niveoguttatus',
                              'Gypaetus barbatus',
                              'Gyps coprotheres',
                              'Neophron percnopterus',
                              'Necrosyrtes monachus',
                              'Torgos tracheliotos',
                              'Gypohierax angolensis',
                              'Gyps rueppelli',
                              'Gyps africanus',
                              'Trigonoceps occipitalis',
                              'Motacilla aguimp',
                              'Motacilla capensis',
                              'Motacilla citreola',
                              'Motacilla cinerea',
                              'Motacilla clara',
                              'Motacilla flava',
                              'Acrocephalus baeticatus',
                              'Bradypterus barratti',
                              'Calamonastes fasciolatus',
                              'Acrocephalus griseldis',
                              'Schoenicola brevirostris',
                              'Euryptila subcinnamomea',
                              'Iduna natalensis',
                              'Acrocephalus scirpaceus',
                              'Sylvia borin',
                              'Acrocephalus arundinaceus',
                              'Hippolais icterina',
                              'Bradypterus sylvaticus',
                              'Acrocephalus gracilirostris',
                              'Bradypterus baboecala',
                              'Acrocephalus palustris',
                              'Phragmacia substriata',
                              'Hippolais olivetorum',
                              'Locustella fluviatilis',
                              'Malcorus pectoralis',
                              'Acrocephalus schoenobaenus',
                              'Calamonastes stierlingi',
                              'Cryptillas victorini',
                              'Phylloscopus trochilus',
                              'Phylloscopus ruficapilla',
                              'Platysteira peltata',
                              'Estrilda erythronotos',
                              'Uraeginthus angolensis',
                              'Estrilda astrild',
                              'Estrilda perreini',
                              'Amandava subflava',
                              'Coccopygia melanotis',
                              'Uraeginthus granatinus',
                              'Ploceus xanthops',
                              'Ploceus capensis',
                              'Ploceus rubiginosus',
                              'Ploceus bicolor',
                              'Ploceus intermedius',
                              'Bubalornis niger',
                              'Anaplectes rubriceps',
                              'Philetairus socius',
                              'Ploceus xanthopterus',
                              'Ploceus velatus',
                              'Ploceus ocularis',
                              'Amblyospiza albifrons',
                              'Ploceus cucullatus',
                              'Ploceus subaureus',
                              'Oenanthe pileata',
                              'Oenanthe monticola',
                              'Oenanthe oenanthe',
                              'Oenanthe pleschanka',
                              'Numenius phaeopus',
                              'Zosterops senegalensis',
                              'Zosterops virens',
                              'Zosterops pallidus',
                              'Sylvia communis',
                              'Vidua obtusa',
                              'Vidua paradisaea',
                              'Vidua macroura',
                              'Vidua regia',
                              'Euplectes axillaris',
                              'Euplectes progne',
                              'Euplectes ardens',
                              'Euplectes albonotatus',
                              'Phoeniculus purpureus',
                              'Dendropicos namaquus',
                              'Campethera bennettii',
                              'Dendropicos fuscescens',
                              'Campethera abingoni',
                              'Geocolaptes olivaceus',
                              'Campethera notata',
                              'Dendropicos griseocephalus',
                              'Jynx ruficollis',
                              'Tringa flavipes']
        for b in birdlife_checklist:
            if not models.Taxon.objects.filter(name=b).first():
                print('BL name does not exist in db ' + b)

        # Retrieve IUCN list of all species in SA to reference against in your recursive tree builder
        r = get_api_info(settings.IUCN_API_OCCURRENCE_URL)
        self.iucn_sa_occurrences = r.json()['result']
        import pdb; pdb.set_trace()
        return
        # Empty taxon table and reload from fixture with base classes (Aves & chiroptera, parents, and unknown)
        models.Taxon.objects.all().delete()

        # Load it all again from the fixture
        call_command('loaddata', 'core_taxon')

        # Select the root items Chiroptera order (bats) & Aves class (birds)
        taxa = models.Taxon.objects.filter(is_root=True)

        # Now all we have left is the items which we need to rebuild the db from
        for taxon in taxa:
            self.recursive_tree_builder(taxon.id)

    def recursive_tree_builder(self, parent_id):
        end_of_records = False
        offset = 0

        while not end_of_records:
            # Get the data
            r = get_api_info(settings.GBIF_API_CHILDREN_URL.format(id=parent_id, offset=offset))

            # Get the jsoned data
            data = r.json()

            # Loop through the children in this result set
            children = data['results']
            for child in children:
                # This is the main ID number in the GBIF system
                taxon_id = int(child['nubKey'])

                # Get the rank key
                rank = False
                for key, value in dict(models.Taxon.RANK_CHOICES).items():
                    if value.lower() == child['rank'].lower():
                        rank = key

                # If we couldn't find it in our list throw an exception
                if not rank:
                    raise ValueError('Rank does not exist in database: ' + child['rank'] + ' For taxon ' +
                                     child['canonicalName'] + '(' + child['rank'] + ') - ' + str(taxon_id))

                # First check the iucn and see if exists in that database
                iucn_category = False
                for occ in self.iucn_sa_occurrences:
                    if occ['scientific_name'].lower() == child['canonicalName'].lower():
                        print('IUCN - ' + occ['scientific_name'] + ' / ' + occ['category'])
                        iucn_category = occ['category']
                        break

                if not iucn_category:
                    # Check and see if there are any SA occurrence records on GBIF
                    r = get_api_info(settings.GBIF_API_OCCURRENCE_URL.format(id=taxon_id, limit=0))

                    # Get the jsoned data
                    occurrences = r.json()

                    print('GBIF - There are ' + str(occurrences['count']) + ' in SA for ' +
                          str(taxon_id) + ' = ' + child['canonicalName'])

                    # Skip this bit of the loop if they're not in SA
                    if occurrences['count'] == 0:
                        continue

                    # Right, so sometimes there's 1 or 2 random specimens stored in museums, these must be eliminated
                    if occurrences['count'] <= 3:
                        r = get_api_info(settings.GBIF_API_OCCURRENCE_URL.format(id=taxon_id,
                                                                                 limit=3) +
                                         '&basisofrecord=PRESERVED_SPECIMEN')
                        records = r.json()['results']

                        valid = False
                        for rec in records:
                            if rec['basisOfRecord'] == 'HUMAN_OBSERVATION':
                                valid = True

                        if not valid:
                            continue

                # Sanity print!
                print(' --- IN SA : ' + child['canonicalName'] + '(' + child['rank'] + ') - ' + str(taxon_id))

                # Populate the taxon object
                taxon = models.Taxon(name=child['canonicalName'],
                                     rank=rank,
                                     id=taxon_id,
                                     parent_id=parent_id)

                # Sometimes we don't have vernac name, so add that only if we have it
                if 'vernacularName' in child:
                    taxon.vernacular_name = child['vernacularName']

                if iucn_category:
                    taxon.red_list = iucn_category

                # Save the taxon
                taxon.save()

                # Recursion
                self.recursive_tree_builder(taxon_id)

            # Are we at the end of the records? if so we need to break out of the loop
            end_of_records = data['endOfRecords']

            # Increase the offset in case we are not at the end of records
            offset += settings.GBIF_API_OFFSET


def sync_iucn_redlisting(request):
    taxa = models.Taxon.objects.all()

    # Loop through allllllll the taxa
    for taxon in taxa:
        r = get_api_info(settings.IUCN_API_URL.format(name=taxon.name))

        # Get the jsoned data
        data = r.json()

        # Set the info if it is available
        result = data['result']
        if result:
            print(str(taxon) + ' - ' + result[0]['category'])
            taxon.red_list = result[0]['category']
        taxon.save()

    # Render the context
    return render_to_response('/admin/',
                              {'message': str(len(taxa)) + ' taxa updated with IUCN redlist statuses'},
                              RequestContext(request))
