# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationdata',
            name='hours',
            field=models.IntegerField(help_text='The number of hours spent doing the surveys'),
        ),
        migrations.AlterField(
            model_name='populationdata',
            name='survey_type',
            field=models.ManyToManyField(blank=True, help_text='Type of survey(s) used during data collection', null=True, to='core.SurveyType'),
        ),
        migrations.AlterField(
            model_name='surveytype',
            name='survey_type',
            field=models.CharField(choices=[('W', 'Walked transect'), ('D', 'Driven transect'), ('P', 'Static point'), ('C', 'Census'), ('I', 'Incidental'), ('R', 'Radar')], max_length=1),
        ),
    ]
