# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 10:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmake',
            name='name',
            field=models.CharField(help_text='Enter name of equipment make. For solar panels add "PV" or "HCPV" to the make.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction_date',
            field=models.DateField(blank=True, help_text='The date construction began on the project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_height',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, help_text='The collision risk range. Drag slider handlers to move range', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='operational_date',
            field=models.DateField(blank=True, help_text='E.g. The day on which the turbines first began revolving', null=True),
        ),
    ]
