# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 08:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160302_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationdata',
            name='survey_type_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('W', 'Walked transect'), ('D', 'Driven transect'), ('P', 'Static point'), ('C', 'Census'), ('I', 'Incidental'), ('R', 'Radar')], default='C', max_length=1), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='focalsitedata',
            name='activity',
            field=models.CharField(blank=True, choices=[('CDP', 'Courtship display'), ('CAN', 'Adult bird carrying nesting material'), ('ANB', 'Active nest building'), ('NCN', 'Newly completed nest'), ('NWE', 'Nest with eggs'), ('NWC', 'Nest with chicks'), ('PFY', 'Parents feeding young in nest'), ('PFS', 'Parents with fecal sac'), ('PAY', 'Parents and young not in nest'), ('NES', 'Nesting'), ('FOR', 'Foraging'), ('RES', 'Resting'), ('TRA', 'Travelling'), ('NON', 'None')], help_text='Activity (only <br>applicable to birds)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='focalsitedata',
            name='life_stage',
            field=models.CharField(blank=True, choices=[('C', 'Chick/pup'), ('J', 'Juvenile'), ('A', 'Adult'), ('U', 'Unknown')], default='A', help_text='Life<br>stage', max_length=1, null=True),
        ),
    ]
