# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 06:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160218_0759'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='taxon',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
