# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 11:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160218_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationdata',
            name='flight_height',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(help_text='Bird flight/Bat equipment<br>height range (m) Format: "x-y" - e.g. "0-1".'),
        ),
    ]
