# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160218_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='solar_panel_locations',
            new_name='solar_locations',
        ),
        migrations.AlterField(
            model_name='project',
            name='energy_type',
            field=models.CharField(choices=[('W', 'Wind'), ('S', 'Solar')], default='W', help_text='The type of renewable energy', max_length=1),
        ),
    ]
