# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160221_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 21, 15, 2, 48, 182736, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
