# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 13:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_project_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focalsite',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(help_text='The area of the focal site, should be within 30km of the project area or it will not be associated with this project. <a href="#" onClick="startIntro()"  data-toggle="tooltip" data-placement="right" title="Click to learn how to use our maps">Learn how to use the map. You can load a KML or GPX, or draw a shape manually          <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span></a>.', srid=4326),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
