# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 05:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160223_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('E', 'EIA report'), ('G', 'Geographic data'), ('O', 'Other'), ('R', 'Raw data')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='focalsitedata',
            name='activity',
            field=models.CharField(blank=True, choices=[('CDP', 'Courtship display'), ('CAN', 'Adult bird carrying nesting material'), ('ANB', 'Active nest building'), ('NCN', 'Newly completed nest'), ('NWE', 'Nest with eggs'), ('NWC', 'Nest with chicks'), ('PFY', 'Parents feeding young in nest'), ('PFS', 'Parents with fecal sac'), ('PAY', 'Parents and young not in nest'), ('NON', 'None')], help_text='Activity (only <br>applicable to birds)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='populationdata',
            name='flight_height',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, help_text='Bird flight/Bat equipment<br>height range (m) Format: "x-y" - e.g. "0-1".', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(help_text='This should give users a rough idea of the study area. <a href="#" onClick="startIntro()"  data-toggle="tooltip" data-placement="right" title="Click to learn how to use our maps">Learn how to use the map. You can load a KML or GPX, or draw a shape manually          <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span></a>.', srid=4326),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='red_list',
            field=models.CharField(blank=True, choices=[('EX', 'Extinct'), ('EW', 'Extinct in the Wild'), ('CR', 'Critically Endangered'), ('EN', 'Endangered'), ('VU', 'Vulnerable'), ('NT', 'Near Threatened'), ('LC', 'Least Concern'), ('DD', 'Data Deficient')], max_length=2, null=True),
        ),
    ]
